### ISSUE TITLE
Should the Manager class handle multiple drivers?

### ISSUE THREAD

**Issue by driesvints** [BeatSwitch/lock#3]
Currently the Manager class accepts a single driver to store all permissions. I was thinking about allowing multiple drivers to be set. So some can be ready only with the `storePermission` and `deletePermission` methods not do anything on a read-only driver. But then you can do things like:

```php
$manager->driver('production')->caller($caller)->can(...)
$manager->driver('local')->caller($user)->can(...)
```

This makes it easy to determine permissions locally for production settings.

Would this be a nice to have?

**Comment by sagikazarmark** [comment]
Hey, just found this package. Coming from sentry (crying for sentinel being open source) this one is the heaven itself.

To respond to this one as well: I think this belongs to a dependency container. Even when using multiple instances.

**Comment by driesvints** [comment]
@sagikazarmark Hey there! First of all, thanks for the nice words! :)

You're probably right about that. I guess the developer can always choose to bind as many Manager instances as he likes into some sort of container. Closing this.
