### ISSUE TITLE
Discussion: tagging stable

### ISSUE THREAD

**Issue by njohns-grovo** [BeatSwitch/lock#43]
Good Evening!
I'm opening this issue as a discussion to find out what is left for this to be tagged as 1.0 stable?  This pr ( #42 ) exists to provide an easy transition path to that in the interim but it would be great to get this `1.0-stable` :)

**Comment by driesvints** [comment]
I won't tag stable any time soon. Don't have time atm to work on the last features, cleanup and documentation updates which I'd like to do before tagging 1.0

For now, I'm going to stick with `0.x` releases.
