### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by CarlosJa** [BeatSwitch/lock#54]
Is there a DB Schema? I can't seem to find it in this Repo...

**Comment by Garbee** [comment]
Persistence is all up to your to determine for your project based on your needs.

**Comment by brazorf** [comment]
This library offers in memory storage out of the box. For a sample database implementation see lock-laravel

**Comment by driesvints** [comment]
Yup, persistence isn't a concern for this library. Like @brazorf said, have a look at the Laravel Lock repo: https://github.com/BeatSwitch/lock-laravel
