### ISSUE TITLE
Implement $lock->clear() method?

### ISSUE THREAD

**Issue by driesvints** [BeatSwitch/lock#6]
Would it make sense to implement a `clear` method for a lock instance to clear any matching permissions, either privileges or restrictions? This could be an easy way to clear permissions to get a fresh start. But I'm not sure if it would be very useful for many people.

The api would be:

```
public function clear(
    string|array $action,
    string|\BeatSwitch\Lock\Contracts\Resource $resource = null,
    int $resourceId = null
)
```

Thoughts?

**Comment by cegrif01** [comment]
I can see that being pretty useful.  During testing, I find myself having to run a migrate:refresh --seed to get a blank slate, so I can see exactly what changed when I set permissions.

**Comment by driesvints** [comment]
@cegrif01 that's something I'd recommend doing every time anyway in your PHPUnit `setUp` method. Remember that Laravel has a neat helper method for that `$this->seed()`. Check http://laravel.com/docs/4.2/testing#helper-methods

I think the `clear` method would be appropriate if you would clear all the permissions for a certain caller or role or for the specified parameters.

**Comment by simsim2006** [comment]
+1

This make really sense ! In my case, I would like to be able to remove explicit permission (deny/allow) of a caller and let the roles (inherited by him) determine if he can perform an action on a resource

**Comment by driesvints** [comment]
This has now been added in #41. Docs update and new release coming soon.

**Comment by driesvints** [comment]
Docs added: https://github.com/BeatSwitch/lock#clearing-permissions
